### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # path to deepseed config

### dataset
dataset_dir: LLaMA-Factory/data # path to dataset_info.json
# dataset: minicheck+anli
dataset: sft_data
template: llama3
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: ./sft_model/ # path to sft-initialized model
logging_steps: 20
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
seed: 42
ddp_timeout: 180000000
resume_from_checkpoint: null
